### ISSUE TITLE
analytics.page() fetching the wrong page title

### ISSUE THREAD

**Issue by paolotim** [thetre97/gridsome-plugin-segment-js#3]
First of all I would like to thank for making this plugin available. It making my work much simpler.

I am not sure if I am making a mistake or there is a bug.  I have installed the plug and in any page I want to track I just add:

mounted ()
  analytics.page('category', 'name')

All the pages track properly for every pageview and all the attributes but title: have the proper information. Instead of returning the title of the current page as indicated in the browser tab, the value returned is the title of the previous page. Any suggestion on how to fix this?

Thanks

**Comment by travis-r6s** [comment]
Hey @paolotim,

That's strange - not sure why it would be doing that. Perhaps the metaInfo JS is slower to change the page title than analytics is to get it and fire the event.
But a fix might be to manually add the page title - https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#page. 
Something like this:
```vue
mounted () {
    this.$analytics.page('category', 'name', { title: this.$metaInfo.title })
}
```

**Comment by paolotim** [comment]
Hey Travis,

Thanks for your reply. I tries your suggestion but I cannot make it work. Here is what’s happening.

My current code:

mounted () {
 analytics.page(‘category’, ’name’)
}

With that code the call trigger on any page view, all the information but the title are correct (title is showing the title of the previous page visited)

If I change analytics.page() into this.$analytics.page() the call does not trigger any more

If I try to set a trait with a text string { title: ’this page’ } the call trigger properly, if I change the text string with a var { title: this.$metaInfo.title } the call does not trigger anymore.

I am not sure what I am doing wrong.

Best

On Apr 8, 2020, at 11:48 AM, Travis Reynolds <notifications@github.com> wrote:


Hey @paolotim <https://github.com/paolotim>,

That's strange - not sure why it would be doing that. Perhaps the metaInfo JS is slower to change the page title than analytics is to get it and fire the event.
But a fix might be to manually add the page title - https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#page <https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#page>.
Something like this:

mounted () {
    this.$analytics.page('category', 'name', { title: this.$metaInfo.title })
}

**Comment by travis-r6s** [comment]
Sorry, my mistake - you should use `this.$segment.page(...`.
Have you enabled/disabled the router integration? Using it seems to give the wrong title, but if I disable it with `router: false`, and use the below code, it shows the title correctly:
```js
this.$segment.page('collection', 'name', { title: this.$metaInfo.title })
# example
this.$segment.page(this.$page.post.category, this.$page.post.title, { title: this.$metaInfo.title })
```

**Comment by paolotim** [comment]
Hry Travis,

I added the router: false option to the plugin setting and change the segment call to this.$segment.page() format. Call is triggering but I am still getting the wrong title info (see attachment).



Best

On Apr 8, 2020, at 1:22 PM, Travis Reynolds <notifications@github.com> wrote:


Sorry, my mistake - you should use this.$segment.page(....
Have you enabled/disabled the router integration? Using it seems to give the wrong title, but if I disable it with router: false, and use the below code, it shows the title correctly:

this.$segment.page('collection', 'name')

**Comment by travis-r6s** [comment]
Yes, just calling `.page()` will still give the wrong title - you will need to add the options I specified above...

**Comment by travis-r6s** [comment]
alternatively, you could add a setTimeout to call the page method after a second or so, and it should give the correct title - i.e. `setTimeout(() => this.$segment.page(), 1500)`
