### ISSUE TITLE
Use Segment Consent Manager

### ISSUE THREAD

**Issue by spurredio** [thetre97/gridsome-plugin-segment-js#5]
Hi, 

Do you know a way to use consent manager with this plugin ?

I've try to insert the script [here](https://segment.com/blog/how-to-build-consent-management-into-your-site-in-less-than-a-week/) with vue-head but i got this error when i save or close cookies consent :

Uncaught TypeError: Cannot read property 'identify' of undefined

Thanks in advance !

**Comment by travis-r6s** [comment]
This is just a wrapper for `vue-segment-analytics`, so I would either ask there, or afraid you may have to manually add yourself if that doesn't yet support it - https://github.com/Kapiche/vue-segment-analytics/issues/32
